<?xml version="1.0" encoding="UTF-8"?>
<CustomApplication xmlns="http://soap.sforce.com/2006/04/metadata">
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>HA_Contact_Record_Page</content>
        <formFactor>Small</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Contact</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>View</actionName>
        <comment>Action override created by Lightning App Builder during activation.</comment>
        <content>HA_Contact_Record_Page</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>Contact</pageOrSobjectType>
    </actionOverrides>
    <actionOverrides>
        <actionName>Tab</actionName>
        <content>Home_Page_Systems</content>
        <formFactor>Large</formFactor>
        <skipRecordTypeSelect>false</skipRecordTypeSelect>
        <type>Flexipage</type>
        <pageOrSobjectType>standard-home</pageOrSobjectType>
    </actionOverrides>
    <brand>
        <headerColor>#0F7EDE</headerColor>
        <shouldOverrideOrgTheme>true</shouldOverrideOrgTheme>
    </brand>
    <description>Systems &amp; Development App</description>
    <formFactors>Small</formFactors>
    <formFactors>Large</formFactors>
    <isNavAutoTempTabsDisabled>false</isNavAutoTempTabsDisabled>
    <isNavPersonalizationDisabled>false</isNavPersonalizationDisabled>
    <isNavTabPersistenceDisabled>false</isNavTabPersistenceDisabled>
    <label>S D</label>
    <navType>Standard</navType>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>Standard</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>HA_System_Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>HA_System_Admin</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>HA Donor Care Advisor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>HA Donor Care Advisor</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>HA Donor Care</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>HA Donor Care</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>HA Comms User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>HA Comms User</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Small</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>StandardAul</profile>
    </profileActionOverrides>
    <profileActionOverrides>
        <actionName>View</actionName>
        <content>HA_Contact_Record_Page_Orphan</content>
        <formFactor>Large</formFactor>
        <pageOrSobjectType>Contact</pageOrSobjectType>
        <recordType>Contact.Orphan</recordType>
        <type>Flexipage</type>
        <profile>StandardAul</profile>
    </profileActionOverrides>
    <tabs>standard-home</tabs>
    <tabs>npsp__NPSP_Settings</tabs>
    <tabs>standard-Account</tabs>
    <tabs>standard-Contact</tabs>
    <tabs>standard-Opportunity</tabs>
    <tabs>npsp__General_Accounting_Unit__c</tabs>
    <tabs>Recurring_Donation_Batch_Errors__c</tabs>
    <tabs>npe03__Recurring_Donation__c</tabs>
    <tabs>HA_Payment_Schedule__c</tabs>
    <tabs>standard-report</tabs>
    <tabs>dlrs__ManageLookupRollupSummaries</tabs>
    <tabs>Bulk_Upload_Donations__c</tabs>
    <tabs>Conga_Metadata_Batch__c</tabs>
    <uiType>Lightning</uiType>
    <utilityBar>CG_Dev_App_UtilityBar</utilityBar>
</CustomApplication>
